apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: dpkononovd/pkononov:0.1.0
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "docker"
        ports:
        - containerPort: 8096
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app
  ports:
  - protocol: TCP
    port: 8096
    targetPort: 8096
