apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s # Как часто Prometheus будет собирать метрики

    scrape_configs:
      - job_name: 'financial-claim-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['app:8096']


      - job_name: 'kafka-exporter'
        static_configs:
          - targets: ['kafka-exporter:9308']

      - job_name: 'kafka-jmx-exporter'
        static_configs:
          - targets: ['kafka-0.kafka:5556']
      
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics:8080']

      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter-prometheus-node-exporter:9100']
