apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-jmx-exporter
data:
  jmx_exporter_config.yaml: |
    lowercaseOutputName: true
    rules:
      - pattern: "kafka.server<type=BrokerTopicMetrics, name=MessagesInPerSec><>Count"
        name: kafka_server_brokertopicmetrics_messagesin_total
        type: COUNTER
      - pattern: "kafka.server<type=BrokerTopicMetrics, name=BytesInPerSec><>Count"
        name: kafka_server_brokertopicmetrics_bytesin_total
        type: COUNTER
      - pattern: "kafka.server<type=BrokerTopicMetrics, name=BytesOutPerSec><>Count"
        name: kafka_server_brokertopicmetrics_bytesout_total
        type: COUNTER
