apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      # Kafka container
      - name: kafka
        image: bitnami/kafka:latest
        env:
        - name: KAFKA_CFG_PROCESS_ROLES
          value: "broker,controller"
        - name: KAFKA_CFG_NODE_ID
          value: "1"
        - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
          value: "1@kafka-0.kafka:9093"
        - name: KAFKA_CFG_LISTENERS
          value: "PLAINTEXT://:9092,CONTROLLER://:9093"
        - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
          value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka-0.kafka:9092"
        - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
          value: "CONTROLLER"
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_CFG_LOG_RETENTION_HOURS
          value: "169"
        - name: KAFKA_CFG_DEFAULT_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_JMX_OPTS
          value: " -Dcom.sun.management.jmxremote \
                   -Dcom.sun.management.jmxremote.authenticate=false \
                   -Dcom.sun.management.jmxremote.ssl=false \
                   -Dcom.sun.management.jmxremote.port=7071 \
                   -Dcom.sun.management.jmxremote.rmi.port=7071 \
                   -Djava.rmi.server.hostname=kafka-0"
        ports:
        - containerPort: 9092
        - containerPort: 9093
        - containerPort: 7071 # JMX port
        - containerPort: 5556 # Metrics port for JMX Exporter
        volumeMounts:
        - name: kafka-storage
          mountPath: /bitnami/kafka

      # JMX Exporter sidecar container
      - name: jmx-exporter
        image: bitnami/jmx-exporter:latest
        ports:
        - containerPort: 5556
          name: metrics

      volumes:
      - name: kafka-storage
        persistentVolumeClaim:
          claimName: kafka-storage

  volumeClaimTemplates:
  - metadata:
      name: kafka-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  clusterIP: None
  selector:
    app: kafka
  ports:
  - port: 9092
    name: kafka
  - port: 9093
    name: controller
  - port: 5556
    name: metrics # Добавляем порт для метрик JMX Exporter
  - port: 7071
    name: jmx
