apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-exporter
  template:
    metadata:
      labels:
        app: kafka-exporter
    spec:
      containers:
      - name: kafka-exporter
        image: bitnami/kafka-exporter:latest
        env:
        - name: KAFKA_BROKERS
          value: "kafka-0.kafka:9092"
        ports:
        - containerPort: 9308
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-exporter
spec:
  selector:
    app: kafka-exporter
  ports:
  - protocol: TCP
    port: 9308
    targetPort: 9308
