spring:
  application:
    name: financial-claim-service
  datasource:
    url: jdbc:postgresql://postgres:5432/test
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: create-drop
  quartz:
    job-store-type: jdbc
    auto-startup: true
    wait-for-jobs-to-complete-on-shutdown: true
    scheduler-name: bookkeeping-scheduler
    jdbc:
      initialize-schema: never
    properties:
      org.quartz.jobStore.class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
      org.quartz.jobStore.isClustered: true
      org.quartz.jobStore.clusterCheckinInterval: 2000
      org.quartz.scheduler.instanceId: AUTO
  financial-claim:
    settings:
      quartz:
        cron-expression: '*/5 * * ? * *'
  kafka:
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  cloud:
    function:
      definition: >
        extFinancialClaimsInitiatedEvent;
        claimsCreatedEvent;
    stream:
      binders:
        kafka-demo:
          type: kafka
          environment:
            spring.cloud.stream.kafka.binder.brokers: kafka:9092
      bindings:
        extFinancialClaimsInitiatedEvent-in-0:
          destination: EXT_FINANCIAL-CLAIMS-INITIATED-CREATED_EVENT
        claimsInitiatedCreatedEvent-out-0:
          destination: CLAIMS_INITIATED-CREATED_EVENT
      default:
        binder: kafka-demo
        content-type: application/json
        group: financial-claims
      kafka:
        bindings:
          default:
            producer:
              sync: true
    consul:
      discovery:
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  h2:
    console:
      enabled: true
server:
  port: 8096
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    tags:
      application: financial-claim-service
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
